name: mecanico_virtual
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  # Si tu Dart no es 3.8.1, relajá el constraint:
  # sdk: ">=3.0.0 <4.0.0"
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.2.3
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.8
  flutter_tts: ^3.6.3
  # path_provider: ^2.1.3   # ❌ en Web no lo uses (lo reemplazamos con shared_preferences)
  uuid: ^4.4.0
  audioplayers: ^5.2.1
  intl_phone_field: ^3.2.0
  flutter_dotenv: ^5.2.1
  path_provider: ^2.1.4
  just_audio: ^0.9.42
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/marcas_modelos.json
    - assets/cacho_bujia.png    
    - assets/bg_gears.png       
    - assets/cacho_bujia_pulgar_arriba.png
    - assets/env.json
    - assets/ch_c1.png