// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqXpbmiRU7iUZgN4HVKiWXrItynnnwXrI',
    appId: '1:508401634531:web:44c74da50e23cdf10a89d6',
    messagingSenderId: '508401634531',
    projectId: 'mecanico-virtual-8f569',
    authDomain: 'mecanico-virtual-8f569.firebaseapp.com',
    storageBucket: 'mecanico-virtual-8f569.firebasestorage.app',
    measurementId: 'G-6CQQGC1YW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzFBTmfHpJuY9R8qiMJSsnWMbd0A9xoAo',
    appId: '1:508401634531:android:f0ec9a9a477150e60a89d6',
    messagingSenderId: '508401634531',
    projectId: 'mecanico-virtual-8f569',
    storageBucket: 'mecanico-virtual-8f569.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcaRg0g3onKCzVu5HFYMeU7kpCvYyXKmc',
    appId: '1:508401634531:ios:5b3ee3be342635df0a89d6',
    messagingSenderId: '508401634531',
    projectId: 'mecanico-virtual-8f569',
    storageBucket: 'mecanico-virtual-8f569.firebasestorage.app',
    iosBundleId: 'com.dariocruz.mecanicoVirtual',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcaRg0g3onKCzVu5HFYMeU7kpCvYyXKmc',
    appId: '1:508401634531:ios:5b3ee3be342635df0a89d6',
    messagingSenderId: '508401634531',
    projectId: 'mecanico-virtual-8f569',
    storageBucket: 'mecanico-virtual-8f569.firebasestorage.app',
    iosBundleId: 'com.dariocruz.mecanicoVirtual',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqXpbmiRU7iUZgN4HVKiWXrItynnnwXrI',
    appId: '1:508401634531:web:0aaa0eefbd00d0f50a89d6',
    messagingSenderId: '508401634531',
    projectId: 'mecanico-virtual-8f569',
    authDomain: 'mecanico-virtual-8f569.firebaseapp.com',
    storageBucket: 'mecanico-virtual-8f569.firebasestorage.app',
    measurementId: 'G-DZ6XQYMHL8',
  );
}
